'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4927
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por wsdl, Versión=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="ServWebConverTempsSoap", [Namespace]:="http://atc.uah.es/ServiciosWeb/")>  _
Partial Public Class ServWebConverTemps
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private ConvFahrACentOperationCompleted As System.Threading.SendOrPostCallback
    
    Private ConvCentAFahrOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost/ServWebConverTemps/ServWebConverTemps.asmx"
    End Sub
    
    '''<remarks/>
    Public Event ConvFahrACentCompleted As ConvFahrACentCompletedEventHandler
    
    '''<remarks/>
    Public Event ConvCentAFahrCompleted As ConvCentAFahrCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://atc.uah.es/ServiciosWeb/ConvFahrACent", RequestNamespace:="http://atc.uah.es/ServiciosWeb/", ResponseNamespace:="http://atc.uah.es/ServiciosWeb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function ConvFahrACent(ByVal gFahr As Double) As Double
        Dim results() As Object = Me.Invoke("ConvFahrACent", New Object() {gFahr})
        Return CType(results(0),Double)
    End Function
    
    '''<remarks/>
    Public Function BeginConvFahrACent(ByVal gFahr As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("ConvFahrACent", New Object() {gFahr}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndConvFahrACent(ByVal asyncResult As System.IAsyncResult) As Double
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Double)
    End Function
    
    '''<remarks/>
    Public Overloads Sub ConvFahrACentAsync(ByVal gFahr As Double)
        Me.ConvFahrACentAsync(gFahr, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub ConvFahrACentAsync(ByVal gFahr As Double, ByVal userState As Object)
        If (Me.ConvFahrACentOperationCompleted Is Nothing) Then
            Me.ConvFahrACentOperationCompleted = AddressOf Me.OnConvFahrACentOperationCompleted
        End If
        Me.InvokeAsync("ConvFahrACent", New Object() {gFahr}, Me.ConvFahrACentOperationCompleted, userState)
    End Sub
    
    Private Sub OnConvFahrACentOperationCompleted(ByVal arg As Object)
        If (Not (Me.ConvFahrACentCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent ConvFahrACentCompleted(Me, New ConvFahrACentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://atc.uah.es/ServiciosWeb/ConvCentAFahr", RequestNamespace:="http://atc.uah.es/ServiciosWeb/", ResponseNamespace:="http://atc.uah.es/ServiciosWeb/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function ConvCentAFahr(ByVal gCent As Double) As Double
        Dim results() As Object = Me.Invoke("ConvCentAFahr", New Object() {gCent})
        Return CType(results(0),Double)
    End Function
    
    '''<remarks/>
    Public Function BeginConvCentAFahr(ByVal gCent As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("ConvCentAFahr", New Object() {gCent}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndConvCentAFahr(ByVal asyncResult As System.IAsyncResult) As Double
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Double)
    End Function
    
    '''<remarks/>
    Public Overloads Sub ConvCentAFahrAsync(ByVal gCent As Double)
        Me.ConvCentAFahrAsync(gCent, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub ConvCentAFahrAsync(ByVal gCent As Double, ByVal userState As Object)
        If (Me.ConvCentAFahrOperationCompleted Is Nothing) Then
            Me.ConvCentAFahrOperationCompleted = AddressOf Me.OnConvCentAFahrOperationCompleted
        End If
        Me.InvokeAsync("ConvCentAFahr", New Object() {gCent}, Me.ConvCentAFahrOperationCompleted, userState)
    End Sub
    
    Private Sub OnConvCentAFahrOperationCompleted(ByVal arg As Object)
        If (Not (Me.ConvCentAFahrCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent ConvCentAFahrCompleted(Me, New ConvCentAFahrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub ConvFahrACentCompletedEventHandler(ByVal sender As Object, ByVal e As ConvFahrACentCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class ConvFahrACentCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Double
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Double)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub ConvCentAFahrCompletedEventHandler(ByVal sender As Object, ByVal e As ConvCentAFahrCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class ConvCentAFahrCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Double
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Double)
        End Get
    End Property
End Class
